(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	image1 - mode
	spectrograph2 - mode
	thermograph0 - mode
	star0 - direction
	groundstation1 - direction
	groundstation2 - direction
	phenomenon3 - direction
	phenomenon4 - direction
	star5 - direction
	phenomenon6 - direction
)
(:init
	(= (slewtime groundstation2 groundstation2) 0)
	(= (slewtime phenomenon3 phenomenon3) 0)
	(= (slewtime phenomenon4 phenomenon4) 0)
	(= (slewtime phenomenon6 phenomenon6) 0)
	(= (slewtime groundstation1 groundstation1) 0)
	(= (slewtime star0 star0) 0)
	(= (slewtime star5 star5) 0)
	(= (data groundstation2 thermograph0) 0)
	(= (data groundstation2 spectrograph2) 0)
	(= (data groundstation2 image1) 0)
	(= (data groundstation1 thermograph0) 0)
	(= (data groundstation1 spectrograph2) 0)
	(= (data groundstation1 image1) 0)
	(= (data star0 thermograph0) 0)
	(= (data star0 spectrograph2) 0)
	(= (data star0 image1) 0)
	(supports instrument0 thermograph0)
	(calibrationtarget instrument0 groundstation2)
	(onboard instrument0 satellite0)
	(poweravail satellite0)
	(pointing satellite0 phenomenon6)
	(= (datacapacity satellite0) 1000)
	(= (fuel satellite0) 112)
	(= (data phenomenon3 image1) 22)
	(= (data phenomenon4 image1) 120)
	(= (data star5 image1) 203)
	(= (data phenomenon6 image1) 144)
	(= (data phenomenon3 spectrograph2) 125)
	(= (data phenomenon4 spectrograph2) 196)
	(= (data star5 spectrograph2) 68)
	(= (data phenomenon6 spectrograph2) 174)
	(= (data phenomenon3 thermograph0) 136)
	(= (data phenomenon4 thermograph0) 134)
	(= (data star5 thermograph0) 273)
	(= (data phenomenon6 thermograph0) 219)
	(= (slewtime groundstation1 star0) 18)
	(= (slewtime star0 groundstation1) 18)
	(= (slewtime groundstation2 star0) 38)
	(= (slewtime star0 groundstation2) 38)
	(= (slewtime groundstation2 groundstation1) 68)
	(= (slewtime groundstation1 groundstation2) 68)
	(= (slewtime phenomenon3 star0) 14)
	(= (slewtime star0 phenomenon3) 14)
	(= (slewtime phenomenon3 groundstation1) 89)
	(= (slewtime groundstation1 phenomenon3) 89)
	(= (slewtime phenomenon3 groundstation2) 33)
	(= (slewtime groundstation2 phenomenon3) 33)
	(= (slewtime phenomenon4 star0) 35)
	(= (slewtime star0 phenomenon4) 35)
	(= (slewtime phenomenon4 groundstation1) 31)
	(= (slewtime groundstation1 phenomenon4) 31)
	(= (slewtime phenomenon4 groundstation2) 39)
	(= (slewtime groundstation2 phenomenon4) 39)
	(= (slewtime phenomenon4 phenomenon3) 25)
	(= (slewtime phenomenon3 phenomenon4) 25)
	(= (slewtime star5 star0) 36)
	(= (slewtime star0 star5) 36)
	(= (slewtime star5 groundstation1) 8)
	(= (slewtime groundstation1 star5) 8)
	(= (slewtime star5 groundstation2) 62)
	(= (slewtime groundstation2 star5) 62)
	(= (slewtime star5 phenomenon3) 10)
	(= (slewtime phenomenon3 star5) 10)
	(= (slewtime star5 phenomenon4) 64)
	(= (slewtime phenomenon4 star5) 64)
	(= (slewtime phenomenon6 star0) 77)
	(= (slewtime star0 phenomenon6) 77)
	(= (slewtime phenomenon6 groundstation1) 17)
	(= (slewtime groundstation1 phenomenon6) 17)
	(= (slewtime groundstation1 phenomenon3) 89)
	(= (slewtime phenomenon3 groundstation2) 33)
	(= (slewtime groundstation2 phenomenon3) 33)
	(= (slewtime phenomenon4 star0) 35)
	(= (slewtime star0 phenomenon4) 35)
	(= (slewtime phenomenon4 groundstation1) 31)
	(= (slewtime groundstation1 phenomenon4) 31)
	(= (slewtime phenomenon4 groundstation2) 39)
	(= (slewtime groundstation2 phenomenon4) 39)
	(= (slewtime phenomenon4 phenomenon3) 25)
	(= (slewtime phenomenon6 groundstation2) 50)
	(= (slewtime groundstation2 phenomenon6) 50)
	(= (slewtime phenomenon6 phenomenon3) 14)
	(= (slewtime phenomenon3 phenomenon6) 14)
	(= (slewtime phenomenon6 phenomenon4) 2)
	(= (slewtime phenomenon4 phenomenon6) 2)
	(= (slewtime phenomenon6 star5) 29)
	(= (slewtime star5 phenomenon6) 29)
	(= (data-stored) 0)
	
	
)
(:goal (and
	(haveimage phenomenon4 thermograph0)
	(haveimage star5 thermograph0)
	(haveimage phenomenon6 thermograph0)
))





)
